# Generated by Django 5.0.2 on 2024-03-11 03:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='back_image',
        ),
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.getFileName),
        ),
        migrations.AddField(
            model_name='product',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.getFileName),
        ),
        migrations.AddField(
            model_name='product',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.getFileName),
        ),
    ]
