# Generated by Django 5.0.2 on 2024-03-12 11:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_image', models.ImageField(blank=True, null=True, upload_to=app.models.getFileName)),
                ('person_name', models.CharField(max_length=50)),
                ('person_review', models.TextField(max_length=500)),
                ('person_role_company', models.CharField(max_length=50)),
            ],
        ),
    ]
